service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: eu-west-1
  iam:
    role: arn:aws:iam::726228754629:role/DynamoDBLambdaAccessRole
  environment:
    PRODUCTS_TABLE: products
    STOCKS_TABLE: stocks
    REGION: eu-west-1

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    includeModules: false
    webpackConfig: "webpack.config.cjs" # Name of webpack configuration file

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true

  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: product/{id}
          method: get
          cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: products

    StocksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: stocks
