service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: eu-west-1
  environment:
    REGION: eu-west-1
    BUCKET: import-service-serverless

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    includeModules: false
    webpackConfig: "webpack.config.cjs" # Name of webpack configuration file

iamRoleStatements:
  - Effect: "Allow"
    Action: "s3:ListBucket"
    Resource:
      - "arn:aws:s3:::import-service-serverless"
  - Effect: "Allow"
    Action: "s3:*"
    Resource:
      - "arn:aws:s3:::import-service-serverless/*"

functions:
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
